CREATE TABLE MANAGEMENT_USER
(
    ID                  BIGSERIAL PRIMARY KEY,
    EMAIL               CHARACTER VARYING(30)    NOT NULL UNIQUE,
    PASSWORD            CHARACTER(60)            NOT NULL,
    FIRST_NAME          CHARACTER VARYING(30)    NOT NULL,
    LAST_NAME           CHARACTER VARYING(30)    NOT NULL,
    VERSION             BIGINT                   NOT NULL      DEFAULT 0,
    CREATED_DATE        TIMESTAMP WITH TIME ZONE NOT NULL      DEFAULT NOW(),
    LAST_MODIFIED_DATE  TIMESTAMP WITH TIME ZONE NOT NULL      DEFAULT NOW(),
    CREATED_BY_ID       BIGINT REFERENCES MANAGEMENT_USER (ID) DEFAULT 1,
    LAST_MODIFIED_BY_ID BIGINT REFERENCES MANAGEMENT_USER (ID) DEFAULT 1
);

CREATE TABLE MANAGEMENT_ROLE
(
    ID                  BIGSERIAL PRIMARY KEY,
    ROLE                CHARACTER VARYING(50)                  NOT NULL,
    DESCRIPTION         CHARACTER VARYING(50)                  NOT NULL,
    VERSION             BIGINT                                 NOT NULL DEFAULT 0,
    CREATED_DATE        TIMESTAMP WITH TIME ZONE               NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE  TIMESTAMP WITH TIME ZONE               NOT NULL DEFAULT NOW(),
    CREATED_BY_ID       BIGINT REFERENCES MANAGEMENT_USER (ID) NOT NULL DEFAULT 1,
    LAST_MODIFIED_BY_ID BIGINT REFERENCES MANAGEMENT_USER (ID) NOT NULL DEFAULT 1
);