CREATE TABLE ORDER_TYPE
(
    ID                  BIGSERIAL PRIMARY KEY,
    VALUE               CHARACTER VARYING(50)    NOT NULL,
    VERSION             BIGINT                   NOT NULL      DEFAULT 0,
    CREATED_DATE        TIMESTAMP WITH TIME ZONE NOT NULL      DEFAULT NOW(),
    LAST_MODIFIED_DATE  TIMESTAMP WITH TIME ZONE NOT NULL      DEFAULT NOW(),
    CREATED_BY_ID       BIGINT REFERENCES MANAGEMENT_USER (ID) DEFAULT 1,
    LAST_MODIFIED_BY_ID BIGINT REFERENCES MANAGEMENT_USER (ID) DEFAULT 1
);

CREATE TABLE ORDER_INFO
(
    ID                  BIGSERIAL PRIMARY KEY,
    VALUE               CHARACTER VARYING(50)             NOT NULL,
    ORDER_TYPE_ID       BIGINT REFERENCES ORDER_TYPE (ID) NOT NULL,
    SALARY              NUMERIC(3)                        NOT NULL,
    VERSION             BIGINT                            NOT NULL DEFAULT 0,
    CREATED_DATE        TIMESTAMP WITH TIME ZONE          NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE  TIMESTAMP WITH TIME ZONE          NOT NULL DEFAULT NOW(),
    CREATED_BY_ID       BIGINT REFERENCES MANAGEMENT_USER (ID)     DEFAULT 1,
    LAST_MODIFIED_BY_ID BIGINT REFERENCES MANAGEMENT_USER (ID)     DEFAULT 1
);

