CREATE TABLE WEBSITE_USER
(
    ID                  BIGSERIAL PRIMARY KEY,
    EMAIL               CHARACTER VARYING(30)                  NOT NULL UNIQUE,
    DESCRIPTION         CHARACTER VARYING(50)                  NOT NULL,
    ORDER_ID            BIGINT REFERENCES ORDER_INFO (ID)      NOT NULL,
    MANAGEMENT_ROLE     BIGINT REFERENCES MANAGEMENT_ROLE (ID) NOT NULL,
    VERSION             BIGINT                                 NOT NULL DEFAULT 0,
    CREATED_DATE        TIMESTAMP WITH TIME ZONE               NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE  TIMESTAMP WITH TIME ZONE               NOT NULL DEFAULT NOW(),
    CREATED_BY_ID       BIGINT REFERENCES MANAGEMENT_USER (ID)          DEFAULT 1,
    LAST_MODIFIED_BY_ID BIGINT REFERENCES MANAGEMENT_USER (ID)          DEFAULT 1
);



